import {
  User,
  Branch,
  Category,
  Unit,
  Product,
  RawMaterial,
  Recipe,
  DiningTable,
  VipRoom,
  Supplier,
  CustomerGroup,
  Customer,
  PurchaseOrder,
  GRN,
  Promotion,
  Employee,
  JobTitle,
  Shift,
  PosOrder,
  SystemSettings,
  Warehouse,
  InventoryStock,
  InventoryBatch,
  AttendanceRecord,
  PayrollRecord,
  CustomerReturn,
  SupplierReturn,
  WarehouseProduction,
  StockTransfer,
} from "@/types";

export const initialBranches: Branch[] = [
  { id: 1, code: "MAIN", name: "NEXUS Main Outlet", address: "42 Galle Road, Colombo 03", phone: "+94 11 200 0001", isActive: true },
  { id: 2, code: "HYDE", name: "Hyde Park Flagship", address: "18 Hyde Park Corner, Colombo 02", phone: "+94 11 200 0002", isActive: true },
  { id: 3, code: "KANDY", name: "Kandy Express Store", address: "12 Dalada Veediya, Kandy", phone: "+94 81 200 0003", isActive: true },
];

export const initialUsers: (User & { passwordHash: string; pinHash: string })[] = [
  {
    id: 1,
    username: "admin",
    name: "NEXUSPOS Administrator",
    role: "ADMINISTRATOR",
    mustChangePassword: true,
    branchId: 1,
    branchName: "NEXUS Main Outlet",
    passwordHash: "$2a$10$w8sY8sC.d1U9VvW3b8J1QerZ6jG4pY6h1h2z3x4c5v6b7n8m9", // 'password' / demo
    pinHash: "$2a$10$w8sY8sC.d1U9VvW3b8J1QerZ6jG4pY6h1h2z3x4c5v6b7n8m9", // '1234'
    createdAt: "2026-08-01T00:00:00Z",
  },
  {
    id: 2,
    username: "manager",
    name: "Kasun Perera (Store Manager)",
    role: "MANAGER",
    mustChangePassword: false,
    branchId: 1,
    branchName: "NEXUS Main Outlet",
    passwordHash: "$2a$10$w8sY8sC.d1U9VvW3b8J1QerZ6jG4pY6h1h2z3x4c5v6b7n8m9",
    pinHash: "$2a$10$w8sY8sC.d1U9VvW3b8J1QerZ6jG4pY6h1h2z3x4c5v6b7n8m9",
    createdAt: "2026-08-01T00:00:00Z",
  },
  {
    id: 3,
    username: "cashier1",
    name: "Nimali Silva",
    role: "CASHIER",
    mustChangePassword: false,
    branchId: 1,
    branchName: "NEXUS Main Outlet",
    passwordHash: "$2a$10$w8sY8sC.d1U9VvW3b8J1QerZ6jG4pY6h1h2z3x4c5v6b7n8m9",
    pinHash: "$2a$10$w8sY8sC.d1U9VvW3b8J1QerZ6jG4pY6h1h2z3x4c5v6b7n8m9",
    createdAt: "2026-08-01T00:00:00Z",
  },
  {
    id: 4,
    username: "barista1",
    name: "Rohan Fernando (Head Barista)",
    role: "BARISTA",
    mustChangePassword: false,
    branchId: 1,
    branchName: "NEXUS Main Outlet",
    passwordHash: "$2a$10$w8sY8sC.d1U9VvW3b8J1QerZ6jG4pY6h1h2z3x4c5v6b7n8m9",
    pinHash: "$2a$10$w8sY8sC.d1U9VvW3b8J1QerZ6jG4pY6h1h2z3x4c5v6b7n8m9",
    createdAt: "2026-08-01T00:00:00Z",
  },
];

export const initialCategories: Category[] = [
  { id: 1, name: "Beverages", description: "Specialty coffees, teas, smoothies & cold drinks", productCount: 6 },
  { id: 2, name: "Bakery", description: "Freshly baked artisan croissants, pastries & buns", productCount: 4 },
  { id: 3, name: "Savory Items", description: "Gourmet sandwiches, wraps, burgers & toasts", productCount: 4 },
  { id: 4, name: "Desserts", description: "Cakes, cheesecakes & gourmet cookies", productCount: 3 },
  { id: 5, name: "Main Course", description: "Pasta, rice bowls & chef signature plates", productCount: 3 },
];

export const initialUnits: Unit[] = [
  { id: 1, name: "Pieces", abbreviation: "pcs" },
  { id: 2, name: "Kilograms", abbreviation: "kg" },
  { id: 3, name: "Grams", abbreviation: "g" },
  { id: 4, name: "Liters", abbreviation: "L" },
  { id: 5, name: "Milliliters", abbreviation: "ml" },
  { id: 6, name: "Packets", abbreviation: "pkt" },
];

export const initialProducts: Product[] = [
  {
    id: 1,
    sku: "BEV-001",
    barcode: "8901230001",
    name: "Caffe Latte (Large)",
    categoryId: 1,
    categoryName: "Beverages",
    unitId: 1,
    unitName: "pcs",
    retailPrice: 850.0,
    costPrice: 280.0,
    pickmePrice: 975.0,
    uberPrice: 975.0,
    isRecipeBased: true,
    reorderLevel: 25,
    isActive: true,
    stock: 120,
  },
  {
    id: 2,
    sku: "BEV-002",
    barcode: "8901230002",
    name: "Signature Cappuccino",
    categoryId: 1,
    categoryName: "Beverages",
    unitId: 1,
    unitName: "pcs",
    retailPrice: 800.0,
    costPrice: 260.0,
    pickmePrice: 920.0,
    uberPrice: 920.0,
    isRecipeBased: true,
    reorderLevel: 20,
    isActive: true,
    stock: 95,
  },
  {
    id: 3,
    sku: "BEV-003",
    barcode: "8901230003",
    name: "Iced Caramel Macchiato",
    categoryId: 1,
    categoryName: "Beverages",
    unitId: 1,
    unitName: "pcs",
    retailPrice: 950.0,
    costPrice: 320.0,
    pickmePrice: 1090.0,
    uberPrice: 1090.0,
    isRecipeBased: true,
    reorderLevel: 15,
    isActive: true,
    stock: 80,
  },
  {
    id: 4,
    sku: "BEV-004",
    barcode: "8901230004",
    name: "Cold Brew Special",
    categoryId: 1,
    categoryName: "Beverages",
    unitId: 1,
    unitName: "pcs",
    retailPrice: 750.0,
    costPrice: 210.0,
    pickmePrice: 860.0,
    uberPrice: 860.0,
    isRecipeBased: true,
    reorderLevel: 10,
    isActive: true,
    stock: 45,
  },
  {
    id: 5,
    sku: "BAK-001",
    barcode: "8901230005",
    name: "Artisan Butter Croissant",
    categoryId: 2,
    categoryName: "Bakery",
    unitId: 1,
    unitName: "pcs",
    retailPrice: 550.0,
    costPrice: 190.0,
    pickmePrice: 630.0,
    uberPrice: 630.0,
    isRecipeBased: true,
    reorderLevel: 15,
    isActive: true,
    stock: 35,
  },
  {
    id: 6,
    sku: "BAK-002",
    barcode: "8901230006",
    name: "Almond Chocolate Croissant",
    categoryId: 2,
    categoryName: "Bakery",
    unitId: 1,
    unitName: "pcs",
    retailPrice: 700.0,
    costPrice: 260.0,
    pickmePrice: 800.0,
    uberPrice: 800.0,
    isRecipeBased: true,
    reorderLevel: 12,
    isActive: true,
    stock: 28,
  },
  {
    id: 7,
    sku: "SAV-001",
    barcode: "8901230007",
    name: "Grilled Smoked Chicken Sandwich",
    categoryId: 3,
    categoryName: "Savory Items",
    unitId: 1,
    unitName: "pcs",
    retailPrice: 1250.0,
    costPrice: 520.0,
    pickmePrice: 1440.0,
    uberPrice: 1440.0,
    isRecipeBased: true,
    reorderLevel: 8,
    isActive: true,
    stock: 18,
  },
  {
    id: 8,
    sku: "SAV-002",
    barcode: "8901230008",
    name: "Spicy Tuna Melt Panini",
    categoryId: 3,
    categoryName: "Savory Items",
    unitId: 1,
    unitName: "pcs",
    retailPrice: 1100.0,
    costPrice: 460.0,
    pickmePrice: 1265.0,
    uberPrice: 1265.0,
    isRecipeBased: true,
    reorderLevel: 10,
    isActive: true,
    stock: 22,
  },
  {
    id: 9,
    sku: "DES-001",
    barcode: "8901230009",
    name: "New York Cheesecake Slice",
    categoryId: 4,
    categoryName: "Desserts",
    unitId: 1,
    unitName: "pcs",
    retailPrice: 950.0,
    costPrice: 380.0,
    pickmePrice: 1090.0,
    uberPrice: 1090.0,
    isRecipeBased: false,
    reorderLevel: 6,
    isActive: true,
    stock: 14,
  },
  {
    id: 10,
    sku: "DES-002",
    barcode: "8901230010",
    name: "Warm Lava Chocolate Brownie",
    categoryId: 4,
    categoryName: "Desserts",
    unitId: 1,
    unitName: "pcs",
    retailPrice: 750.0,
    costPrice: 280.0,
    pickmePrice: 860.0,
    uberPrice: 860.0,
    isRecipeBased: true,
    reorderLevel: 10,
    isActive: true,
    stock: 30,
  },
  {
    id: 11,
    sku: "MC-001",
    barcode: "8901230011",
    name: "Creamy Chicken Alfredo Pasta",
    categoryId: 5,
    categoryName: "Main Course",
    unitId: 1,
    unitName: "pcs",
    retailPrice: 1650.0,
    costPrice: 680.0,
    pickmePrice: 1890.0,
    uberPrice: 1890.0,
    isRecipeBased: true,
    reorderLevel: 5,
    isActive: true,
    stock: 15,
  },
];

export const initialRawMaterials: RawMaterial[] = [
  { id: 1, code: "RAW-001", name: "Premium Arabica Coffee Beans", unitId: 2, unitName: "kg", costPerUnit: 6500.0, reorderLevel: 20, currentStock: 45.5 },
  { id: 2, code: "RAW-002", name: "Fresh Full-Cream Dairy Milk", unitId: 4, unitName: "L", costPerUnit: 480.0, reorderLevel: 50, currentStock: 120.0 },
  { id: 3, code: "RAW-003", name: "Monin Caramel Flavored Syrup", unitId: 4, unitName: "L", costPerUnit: 4200.0, reorderLevel: 5, currentStock: 14.0 },
  { id: 4, code: "RAW-004", name: "French Unsalted Bakery Butter", unitId: 2, unitName: "kg", costPerUnit: 3400.0, reorderLevel: 15, currentStock: 32.0 },
  { id: 5, code: "RAW-005", name: "Artisan T55 Wheat Pastry Flour", unitId: 2, unitName: "kg", costPerUnit: 380.0, reorderLevel: 100, currentStock: 250.0 },
  { id: 6, code: "RAW-006", name: "Smoked Chicken Breast Slices", unitId: 2, unitName: "kg", costPerUnit: 2400.0, reorderLevel: 10, currentStock: 18.5 },
  { id: 7, code: "RAW-007", name: "Belgian Dark Chocolate Callets 70%", unitId: 2, unitName: "kg", costPerUnit: 5200.0, reorderLevel: 8, currentStock: 16.0 },
];

export const initialRecipes: Recipe[] = [
  {
    id: 1,
    productId: 1,
    productName: "Caffe Latte (Large)",
    name: "Standard Large Latte Spec",
    yieldQuantity: 1,
    instructions: "Grind 18g coffee beans, pull 36ml double espresso shot, steam 220ml milk to 65C with microfoam, pour with heart latte art.",
    isActive: true,
    items: [
      { rawMaterialId: 1, rawMaterialName: "Premium Arabica Coffee Beans", quantity: 0.018, unitName: "kg", unitCost: 117.0 },
      { rawMaterialId: 2, rawMaterialName: "Fresh Full-Cream Dairy Milk", quantity: 0.22, unitName: "L", unitCost: 105.6 },
    ],
    totalCost: 222.6,
  },
  {
    id: 2,
    productId: 3,
    productName: "Iced Caramel Macchiato",
    name: "Iced Caramel Macchiato Formula",
    yieldQuantity: 1,
    instructions: "Add 20ml vanilla syrup and cold milk to ice glass, pour espresso shots on top, drizzle 15ml caramel sauce crosshatch pattern.",
    isActive: true,
    items: [
      { rawMaterialId: 1, rawMaterialName: "Premium Arabica Coffee Beans", quantity: 0.018, unitName: "kg", unitCost: 117.0 },
      { rawMaterialId: 2, rawMaterialName: "Fresh Full-Cream Dairy Milk", quantity: 0.2, unitName: "L", unitCost: 96.0 },
      { rawMaterialId: 3, rawMaterialName: "Monin Caramel Flavored Syrup", quantity: 0.025, unitName: "L", unitCost: 105.0 },
    ],
    totalCost: 318.0,
  },
];

export const initialDiningTables: DiningTable[] = [
  { id: 1, branchId: 1, tableNumber: "T-01", name: "Window Table 1", capacity: 2, status: "AVAILABLE" },
  { id: 2, branchId: 1, tableNumber: "T-02", name: "Window Table 2", capacity: 2, status: "OCCUPIED", currentOrderId: "ORD-20260803-014" },
  { id: 3, branchId: 1, tableNumber: "T-03", name: "Main Hall Center 3", capacity: 4, status: "AVAILABLE" },
  { id: 4, branchId: 1, tableNumber: "T-04", name: "Main Hall Center 4", capacity: 4, status: "RESERVED" },
  { id: 5, branchId: 1, tableNumber: "T-05", name: "Family Booth 5", capacity: 6, status: "AVAILABLE" },
  { id: 6, branchId: 1, tableNumber: "T-06", name: "Outdoor Patio 6", capacity: 4, status: "CLEANING" },
];

export const initialVipRooms: VipRoom[] = [
  { id: 1, branchId: 1, roomNumber: "VIP-A", name: "The Executive Lounge", capacity: 12, minSpend: 25000, hourlyRate: 3500, status: "AVAILABLE" },
  { id: 2, branchId: 1, roomNumber: "VIP-B", name: "The Emerald Suite", capacity: 8, minSpend: 18000, hourlyRate: 2500, status: "OCCUPIED" },
  { id: 3, branchId: 1, roomNumber: "VIP-C", name: "The Wine Cellar Room", capacity: 16, minSpend: 35000, hourlyRate: 5000, status: "AVAILABLE" },
];

export const initialSuppliers: Supplier[] = [
  { id: 1, code: "SUP-001", name: "Ceylon Coffee Roasters Ltd", contactPerson: "Anil Gunawardena", phone: "+94 77 123 4567", email: "orders@ceylonroasters.lk", paymentTerms: "NET 30", balance: 145000 },
  { id: 2, code: "SUP-002", name: "Kotmale Dairies PLC", contactPerson: "Sunil Wickrama", phone: "+94 71 987 6543", email: "sales@kotmaledairy.lk", paymentTerms: "NET 15", balance: 68000 },
  { id: 3, code: "SUP-003", name: "Swiss Gourmet Ingredients", contactPerson: "Elena Meyer", phone: "+94 11 555 4321", email: "info@swissgourmet.lk", paymentTerms: "NET 30", balance: 220000 },
];

export const initialCustomerGroups: CustomerGroup[] = [
  { id: 1, name: "Regular Retail", discountRate: 0, customerCount: 1420 },
  { id: 2, name: "VIP Elite Members", discountRate: 10, customerCount: 86 },
  { id: 3, name: "Corporate Accounts", discountRate: 15, customerCount: 34 },
  { id: 4, name: "Staff & Crew", discountRate: 25, customerCount: 28 },
];

export const initialCustomers: Customer[] = [
  { id: 1, customerCode: "CUST-001", name: "Dr. Dinesh Jayawardena", mobile: "+94 77 345 6789", email: "dinesh.j@gmail.com", groupId: 2, groupName: "VIP Elite Members", discountRate: 10, loyaltyPoints: 1450, outstandingBalance: 0, creditLimit: 50000 },
  { id: 2, customerCode: "CUST-002", name: "Millennium IT Corp", mobile: "+94 11 234 5678", email: "procurement@mit.com", groupId: 3, groupName: "Corporate Accounts", discountRate: 15, loyaltyPoints: 5200, outstandingBalance: 42500, creditLimit: 150000 },
  { id: 3, customerCode: "CUST-003", name: "Sachini Gamage", mobile: "+94 71 876 5432", email: "sachini.g@outlook.com", groupId: 1, groupName: "Regular Retail", discountRate: 0, loyaltyPoints: 340, outstandingBalance: 0, creditLimit: 10000 },
];

export const initialOrders: PosOrder[] = [
  {
    id: "ORD-20260803-001",
    orderNo: "ORD-20260803-001",
    branchId: 1,
    branchName: "NEXUS Main Outlet",
    cashierName: "Nimali Silva",
    customerName: "Walk-in Customer",
    orderType: "DINE_IN",
    items: [
      { productId: 1, productName: "Caffe Latte (Large)", quantity: 2, unitPrice: 850, subtotal: 1700 },
      { productId: 5, productName: "Artisan Butter Croissant", quantity: 2, unitPrice: 550, subtotal: 1100 },
    ],
    subtotal: 2800,
    discountAmount: 0,
    taxAmount: 280,
    serviceCharge: 280,
    totalAmount: 3360,
    paymentMethod: "CARD",
    amountPaid: 3360,
    changeGiven: 0,
    status: "COMPLETED",
    kdsStatus: "SERVED",
    createdAt: "2026-08-03T08:30:00Z",
  },
  {
    id: "ORD-20260803-002",
    orderNo: "ORD-20260803-002",
    branchId: 1,
    branchName: "NEXUS Main Outlet",
    cashierName: "Nimali Silva",
    customerName: "Dr. Dinesh Jayawardena",
    orderType: "TAKEAWAY",
    items: [
      { productId: 3, productName: "Iced Caramel Macchiato", quantity: 1, unitPrice: 950, subtotal: 950 },
      { productId: 7, productName: "Grilled Smoked Chicken Sandwich", quantity: 1, unitPrice: 1250, subtotal: 1250 },
    ],
    subtotal: 2200,
    discountAmount: 220,
    taxAmount: 198,
    serviceCharge: 0,
    totalAmount: 2178,
    paymentMethod: "CASH",
    amountPaid: 2500,
    changeGiven: 322,
    status: "COMPLETED",
    kdsStatus: "READY",
    createdAt: "2026-08-03T09:15:00Z",
  },
];

export const initialPurchaseOrders: PurchaseOrder[] = [
  {
    id: 1,
    poNumber: "PO-2026-0089",
    supplierId: 1,
    supplierName: "Ceylon Coffee Roasters Ltd",
    branchId: 1,
    branchName: "NEXUS Main Outlet",
    totalAmount: 325000,
    status: "APPROVED",
    items: [
      { productId: undefined, rawMaterialId: 1, rawMaterialName: "Premium Arabica Coffee Beans", quantity: 50, unitCost: 6500, totalCost: 325000 },
    ],
    createdAt: "2026-08-01T10:00:00Z",
  },
  {
    id: 2,
    poNumber: "PO-2026-0090",
    supplierId: 2,
    supplierName: "Kotmale Dairies PLC",
    branchId: 1,
    branchName: "NEXUS Main Outlet",
    totalAmount: 96000,
    status: "RECEIVED",
    items: [
      { productId: undefined, rawMaterialId: 2, rawMaterialName: "Fresh Full-Cream Dairy Milk", quantity: 200, unitCost: 480, totalCost: 96000 },
    ],
    createdAt: "2026-08-02T11:30:00Z",
  },
];

export const initialGRNs: GRN[] = [
  {
    id: 1,
    grnNumber: "GRN-2026-0045",
    purchaseOrderId: 2,
    poNumber: "PO-2026-0090",
    supplierId: 2,
    supplierName: "Kotmale Dairies PLC",
    branchId: 1,
    branchName: "NEXUS Main Outlet",
    invoiceNumber: "INV-KOT-9981",
    totalAmount: 96000,
    paidAmount: 96000,
    paymentStatus: "PAID",
    status: "VERIFIED",
    items: [
      { rawMaterialId: 2, rawMaterialName: "Fresh Full-Cream Dairy Milk", quantityReceived: 200, unitCost: 480, totalCost: 96000, batchNumber: "BATCH-MLK-0802", expiryDate: "2026-08-12" },
    ],
    createdAt: "2026-08-02T14:20:00Z",
  },
];

export const initialPromotions: Promotion[] = [
  { id: 1, code: "MORNING15", name: "Early Bird Breakfast 15% Off", type: "PERCENTAGE", discountValue: 15, startDate: "2026-08-01", endDate: "2026-08-31", status: "ACTIVE" },
  { id: 2, code: "COFFEELOVE", name: "Coffee Lover Flat Rs. 100 Off", type: "FIXED_AMOUNT", discountValue: 100, startDate: "2026-08-01", endDate: "2026-08-15", status: "ACTIVE" },
];

export const initialEmployees: Employee[] = [
  { id: 1, employeeCode: "EMP-001", name: "Kasun Perera", jobTitle: "Store Manager", branch: "NEXUS Main Outlet", branchId: 1, mobile: "+94 77 111 2233", email: "kasun@nexuspos.lk", employmentStatus: "ACTIVE", hiredDate: "2024-01-15", salary: 145000 },
  { id: 2, employeeCode: "EMP-002", name: "Nimali Silva", jobTitle: "Head Cashier", branch: "NEXUS Main Outlet", branchId: 1, mobile: "+94 77 222 3344", email: "nimali@nexuspos.lk", employmentStatus: "ACTIVE", hiredDate: "2024-06-01", salary: 75000 },
  { id: 3, employeeCode: "EMP-003", name: "Rohan Fernando", jobTitle: "Senior Barista", branch: "NEXUS Main Outlet", branchId: 1, mobile: "+94 77 333 4455", email: "rohan@nexuspos.lk", employmentStatus: "ACTIVE", hiredDate: "2024-09-10", salary: 85000 },
  { id: 4, employeeCode: "EMP-004", name: "Dilani Bandara", jobTitle: "Pastry Chef", branch: "NEXUS Main Outlet", branchId: 1, mobile: "+94 77 444 5566", email: "dilani@nexuspos.lk", employmentStatus: "ACTIVE", hiredDate: "2025-02-01", salary: 110000 },
];

export const initialJobs: JobTitle[] = [
  { id: 1, title: "Store Manager", department: "Operations", description: "Overall store and team lead", employeeCount: 3 },
  { id: 2, title: "Head Cashier", department: "Front of House", description: "Register operations & cash settlement", employeeCount: 6 },
  { id: 3, title: "Senior Barista", department: "Beverage", description: "Specialty coffee brewing & KDS prep", employeeCount: 8 },
  { id: 4, title: "Pastry Chef", department: "Kitchen", description: "Bakery and dessert preparation", employeeCount: 4 },
];

export const initialShifts: Shift[] = [
  { id: 1, name: "Morning Opening Shift", startTime: "06:30", endTime: "15:00", durationHours: 8.5 },
  { id: 2, name: "Afternoon / Evening Shift", startTime: "14:30", endTime: "23:00", durationHours: 8.5 },
  { id: 3, name: "Mid-day Peak Assist", startTime: "11:00", endTime: "19:30", durationHours: 8.5 },
];

export const initialSettings: SystemSettings = {
  id: 1,
  branchId: 1,
  storeName: "NEXUSPOS Cafe & Restaurant",
  address: "42 Galle Road, Colombo 03, Sri Lanka",
  phone: "+94 11 200 0001",
  receiptHeader: "WELCOME TO NEXUSPOS\nPremium Artisan Cafe & Bakery\nVAT Reg: 409012345-7000",
  receiptFooter: "Thank you for dining with us!\nFollow us @nexuspos.cafe\nWifi: NEXUS-Guest / Pass: coffee2026",
  taxPercentage: 10.0,
  serviceChargePercentage: 10.0,
  currencySymbol: "Rs.",
  isNegativeStockAllowed: false,
};
